import Link from "next/link";
import Head from "next/head";
import { Navbar, NavLink } from "@/components/navbar";
import { Container, Main, Title, Description } from "@/components/sharedstyles";

export default function About() {
  return (
    <Container>
      <Head>
        <title>Kelimela - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Description>
          
        </Description>
        <Navbar>
        <NavLink href="/">Home</NavLink>
        
      </Navbar>
      <Title>@ahmetyigiterdeniz</Title><br></br><br></br><br></br>
      <p>Source code at my GitHub.</p>
      </Main>
    </Container>
  );
}
