import Head from "next/head";
import {
  Container,
  Main
} from "@/components/sharedstyles";
import { Navbar, NavLink } from "@/components/navbar";
import { TextInput, Input, Button, Grid } from "@/components/gamedisplay";
import Row from "@/components/Row";
import { useState } from "react";


export default function Home() {
  const [wordList, setWordList] = useState(["mug", "old", "fun", "let", "man", "men", "fan", "hut", "hat", "lot", "fat", "set", "sat", "ton"]);
  const [chosenWord, setChosenWord] = useState(wordList[(Math.floor(Math.random() * (wordList.length)))]);
  const [guessedWordsList, setGuessedWordsList] = useState([...Array(3)]);
  const [val, setVal] = useState("");
  const [failed, setFailed] = useState(false);
  const [gameState, setGameState] = useState(true);
  const [guessNumber, setGuessNumber] = useState(0);
  const splitChosenWord = chosenWord.split('');

  return (
    <Container>
      <Head>
        <title>Kelimela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <NavLink href="/about">About</NavLink>
      </Navbar>
      <Main>
      <Input><TextInput onChange={(e) => setVal(e.target.value)} value = {val.toLowerCase()} />{gameState === true ? <Button onClick={() => {
        if(val.length === 3){
          if(val===chosenWord){
// TRUE            
            setGameState(false);
            setGuessedWordsList((prevGuesses) => {
              let newGuesses = [...prevGuesses]
              newGuesses[guessNumber] = val
              return newGuesses
            });
          }

          else {
            if(guessNumber === 2 && val !== chosenWord){
// FALSE            
            setGuessedWordsList((prevGuesses) => {
              let newGuesses = [...prevGuesses]
              newGuesses[guessNumber] = val
              return newGuesses
            });

            setTimeout(() => {
              setGameState(false);
              setFailed(true);
              setGuessNumber(guessNumber + 1);}, 2000);
          } 
          
          setGuessedWordsList((prevGuesses) => {
            let newGuesses = [...prevGuesses]
            newGuesses[guessNumber] = val
            return newGuesses
          });
          setGuessNumber(guessNumber + 1);
        }
      } else {
        alert("String must be 3 letters long.")
      }
        }}>Submit</Button> : null}</Input>

        {gameState ? <Grid>
          <Row word={chosenWord} guess={guessedWordsList[0]} />
          <Row word={chosenWord} guess={guessedWordsList[1]} />
          <Row word={chosenWord} guess={guessedWordsList[2]} />
        </Grid> : <><p>You finished game.</p>{val===chosenWord ? <Row word={chosenWord} guess={guessedWordsList[guessNumber]} /> : null}</>}
        {guessNumber === 3 && (guessedWordsList.includes(chosenWord) === false) && (gameState === false)  ? <><p>You failed the game. The word was <b>{chosenWord}</b></p><br></br><Button onClick={() => {
          setGameState(true);
          setGuessNumber(0);
          setGuessedWordsList([undefined, undefined, undefined]);
        }}>Restart</Button></> : null}
      </Main>
    </Container>
  );
}
